/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package package_v2;
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;


/**
 *
 * @author Alexandra
 */
public class JFAddRoom extends javax.swing.JFrame {

    /**
     * Creates new form JFAddSite
     */
    public JFAddRoom() {
        initComponents();
        this.setResizable(false);
        this.jLerr.setVisible(false);
        this.jLerr.setForeground(Color.red);
        DefaultComboBoxModel listSite = new DefaultComboBoxModel();
        listSite=DBMana.selectDBSite(listSite);
        selectSite.setModel(listSite);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLAdd = new javax.swing.JLabel();
        jLSiteName = new javax.swing.JLabel();
        jLTypeRoom = new javax.swing.JLabel();
        jTNumRoom = new javax.swing.JTextField();
        jButtonAddRoom = new javax.swing.JButton();
        jImgAddRoom = new javax.swing.JLabel();
        selectSite = new javax.swing.JComboBox();
        jLNumRoom = new javax.swing.JLabel();
        selectType = new javax.swing.JComboBox();
        jLerr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLAdd.setText("Ajouter une salle");

        jLSiteName.setText("Local : ");

        jLTypeRoom.setText("Type de la salle");

        jButtonAddRoom.setText("Valider");
        jButtonAddRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddRoomActionPerformed(evt);
            }
        });

        jImgAddRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addRoom.png"))); // NOI18N

        jLNumRoom.setText("Numéro de salle : ");

        selectType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TP Réseau", "TP Informatique", "Serveur", "Cours" }));

        jLerr.setText("Texte d'erreur");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jImgAddRoom)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonAddRoom))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNumRoom)
                            .addComponent(jLSiteName)
                            .addComponent(jLTypeRoom))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectSite, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTNumRoom))
                        .addGap(32, 32, 32)))
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLerr)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jImgAddRoom)
                .addGap(34, 34, 34)
                .addComponent(jLerr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLSiteName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTypeRoom))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNumRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNumRoom))
                .addGap(32, 32, 32)
                .addComponent(jButtonAddRoom)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddRoomActionPerformed
        // TODO add your handling code here:
        String roomNum = this.jTNumRoom.getText();
        String siteName = (String)this.selectSite.getSelectedItem();
        String roomType = (String)this.selectType.getSelectedItem();
        
        if(("".equals(roomNum))){
            this.jLerr.setText("Vous avez oublié de remplir un champs");
            this.jLerr.setVisible(true);
        }
        else{
            //test nom salle non existant
            boolean exist = DBMana.roomExist(roomNum, siteName);
            if(!exist){
                this.jLerr.setText("La salle "+roomNum+" existe déjà");
                this.jLerr.setVisible(true);
            }
            else{
                Room room = new Room (siteName, roomNum, roomType);
                DBMana.AddDBRoom(room);
                this.jLerr.setVisible(false);
                JFAddOk addOk = new JFAddOk("salle", "ajoutée");
                addOk.setVisible(true);
                this.setVisible(false);
            }
            
        }
    }//GEN-LAST:event_jButtonAddRoomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAddRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAddRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAddRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAddRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFAddRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddRoom;
    private javax.swing.JLabel jImgAddRoom;
    private javax.swing.JLabel jLAdd;
    private javax.swing.JLabel jLNumRoom;
    private javax.swing.JLabel jLSiteName;
    private javax.swing.JLabel jLTypeRoom;
    private javax.swing.JLabel jLerr;
    private javax.swing.JTextField jTNumRoom;
    private javax.swing.JComboBox selectSite;
    private javax.swing.JComboBox selectType;
    // End of variables declaration//GEN-END:variables
}
