/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package package_v2;
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;


/**
 *
 * @author Alexandra
 */
public class JFAddIntercoDev extends javax.swing.JFrame {

    /**
     * Creates new form JFAddSite
     */
    public JFAddIntercoDev() {
        initComponents();
        this.setResizable(false);
        this.jLerr.setVisible(false);
        this.jLerr.setForeground(Color.red);
        DefaultComboBoxModel listSite = new DefaultComboBoxModel();
        listSite=DBMana.selectDBSite(listSite);
        selectSite.setModel(listSite);
        String siteName = (String)this.selectSite.getSelectedItem();
        DefaultComboBoxModel listSite2 = new DefaultComboBoxModel();
        listSite2=DBMana.selectDBRoom(listSite2, siteName);
        selectRoom.setModel(listSite2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLAdd = new javax.swing.JLabel();
        jLSiteName = new javax.swing.JLabel();
        jLTypeDev = new javax.swing.JLabel();
        jButtonAddIntercoDev = new javax.swing.JButton();
        jImgAddRoom = new javax.swing.JLabel();
        selectSite = new javax.swing.JComboBox();
        jLRoom = new javax.swing.JLabel();
        selectTypeDev = new javax.swing.JComboBox();
        jLerr = new javax.swing.JLabel();
        selectRoom = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLAdd.setText("Ajouter un équipement d'interconnexion");

        jLSiteName.setText("Local : ");

        jLTypeDev.setText("Type d'équipement : ");

        jButtonAddIntercoDev.setText("Valider");
        jButtonAddIntercoDev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddIntercoDevActionPerformed(evt);
            }
        });

        jImgAddRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addDevInterco.png"))); // NOI18N

        selectSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectSiteActionPerformed(evt);
            }
        });

        jLRoom.setText("Salle : ");

        selectTypeDev.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Routeur", "Switch", "Borne Wifi" }));

        jLerr.setText("Texte d'erreur");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonAddIntercoDev)
                        .addGap(67, 67, 67))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLerr)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jImgAddRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLTypeDev)
                                .addGap(36, 36, 36)
                                .addComponent(selectTypeDev, 0, 92, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLSiteName)
                                    .addComponent(jLRoom))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(selectRoom, 0, 92, Short.MAX_VALUE)
                                    .addComponent(selectSite, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(0, 83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jImgAddRoom)
                .addGap(34, 34, 34)
                .addComponent(jLerr)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSiteName)
                    .addComponent(selectSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLRoom)
                    .addComponent(selectRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTypeDev)
                    .addComponent(selectTypeDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jButtonAddIntercoDev)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddIntercoDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddIntercoDevActionPerformed
        // TODO add your handling code here:
        String roomNum = ""; //this.jTNumRoom.getText();
        String siteName = (String)this.selectSite.getSelectedItem();
        String roomType = (String)this.selectTypeDev.getSelectedItem();
        
        if(("".equals(roomNum))){
            this.jLerr.setText("Vous avez oublié de remplir un champs");
            this.jLerr.setVisible(true);
        }
        else{
            //test nom salle non existant
            boolean exist = DBMana.roomExist(roomNum, siteName);
            if(!exist){
                this.jLerr.setText("La salle "+roomNum+" existe déjà");
                this.jLerr.setVisible(true);
            }
            else{
                Room room = new Room (siteName, roomNum, roomType);
                DBMana.AddDBRoom(room);
                this.jLerr.setVisible(false);
                JFAddOk addOk = new JFAddOk("salle", "ajoutée");
                addOk.setVisible(true);
                this.setVisible(false);
            }
            
        }
    }//GEN-LAST:event_jButtonAddIntercoDevActionPerformed

    private void selectSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectSiteActionPerformed
        // TODO add your handling code here:
        String siteName = (String)this.selectSite.getSelectedItem();
        DefaultComboBoxModel listSite = new DefaultComboBoxModel();
        listSite=DBMana.selectDBRoom(listSite, siteName);
        selectRoom.setModel(listSite);
    }//GEN-LAST:event_selectSiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAddIntercoDev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAddIntercoDev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAddIntercoDev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAddIntercoDev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFAddIntercoDev().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddIntercoDev;
    private javax.swing.JLabel jImgAddRoom;
    private javax.swing.JLabel jLAdd;
    private javax.swing.JLabel jLRoom;
    private javax.swing.JLabel jLSiteName;
    private javax.swing.JLabel jLTypeDev;
    private javax.swing.JLabel jLerr;
    private javax.swing.JComboBox selectRoom;
    private javax.swing.JComboBox selectSite;
    private javax.swing.JComboBox selectTypeDev;
    // End of variables declaration//GEN-END:variables
}
