/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package package_v3;

import java.awt.Color;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Alexandra
 */
public class JFAddDev extends javax.swing.JFrame {

    /**
     * Creates new form JFAddDev
     */
    public JFAddDev() {
        initComponents();
        this.jLerr.setVisible(false);
        this.jLerr.setForeground(Color.red);
        DefaultComboBoxModel listSite = new DefaultComboBoxModel();
        listSite=DBMana.selectDBSite(listSite);
        selectSite.setModel(listSite);
        String siteName = (String)this.selectSite.getSelectedItem();
        DefaultComboBoxModel listRoom = new DefaultComboBoxModel();
        listRoom=DBMana.selectDBRoom(listRoom, siteName);
        selectRoom.setModel(listRoom);
        String os = (String)this.selectTypeDev.getSelectedItem();
        if("Ordinateur".equals(os)){
            DefaultComboBoxModel listOs = new DefaultComboBoxModel();
            listOs.addElement("OS x");
            listOs.addElement("Linux");
            listOs.addElement("Windows");
            selectOs.setModel(listOs);
        }else if("Tablette".equals(os)){
            DefaultComboBoxModel listOs = new DefaultComboBoxModel();
            listOs.addElement("iOS");
            listOs.addElement("Androïd");
            listOs.addElement("Windows");
            selectOs.setModel(listOs);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLAddDev = new javax.swing.JLabel();
        jImgAddDev = new javax.swing.JLabel();
        jLerr = new javax.swing.JLabel();
        jLDevName = new javax.swing.JLabel();
        jTDevName = new javax.swing.JTextField();
        selectTypeDev = new javax.swing.JComboBox();
        jLTypeDev = new javax.swing.JLabel();
        selectOs = new javax.swing.JComboBox();
        jLOsDev = new javax.swing.JLabel();
        selectSite = new javax.swing.JComboBox();
        selectRoom = new javax.swing.JComboBox();
        jLSite = new javax.swing.JLabel();
        jLRoom = new javax.swing.JLabel();
        jBOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLAddDev.setText("Ajouter un équipement");

        jImgAddDev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addDev.png"))); // NOI18N

        jLerr.setText("Text d'erreur");

        jLDevName.setText("Nom de l'équipement : ");

        selectTypeDev.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ordinateur", "Tablette" }));
        selectTypeDev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTypeDevActionPerformed(evt);
            }
        });

        jLTypeDev.setText("Type d'équipement :");

        selectOs.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Os" }));

        jLOsDev.setText("OS de l'équipement :");

        selectSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectSiteActionPerformed(evt);
            }
        });

        jLSite.setText("Local : ");

        jLRoom.setText("Salle :");

        jBOk.setText("Valider");
        jBOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLAddDev)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jImgAddDev, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLerr))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLDevName)
                            .addComponent(jLTypeDev)
                            .addComponent(jLOsDev)
                            .addComponent(jLSite)
                            .addComponent(jLRoom))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(selectRoom, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectSite, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectOs, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectTypeDev, javax.swing.GroupLayout.Alignment.TRAILING, 0, 100, Short.MAX_VALUE)
                            .addComponent(jTDevName, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBOk)
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLAddDev)
                .addGap(18, 18, 18)
                .addComponent(jImgAddDev, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLerr)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDevName)
                    .addComponent(jTDevName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectTypeDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTypeDev))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectOs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLOsDev))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectSite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLSite))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLRoom))
                .addGap(26, 26, 26)
                .addComponent(jBOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectSiteActionPerformed
        // TODO add your handling code here:
        String siteName = (String)this.selectSite.getSelectedItem();
        DefaultComboBoxModel listRoom = new DefaultComboBoxModel();
        listRoom=DBMana.selectDBRoom(listRoom, siteName);
        selectRoom.setModel(listRoom);
    }//GEN-LAST:event_selectSiteActionPerformed

    private void selectTypeDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTypeDevActionPerformed
        // TODO add your handling code here:
        String os = (String)this.selectTypeDev.getSelectedItem();
        if("Ordinateur".equals(os)){
            DefaultComboBoxModel listOs = new DefaultComboBoxModel();
            listOs.addElement("OS x");
            listOs.addElement("Linux");
            listOs.addElement("Windows");
            selectOs.setModel(listOs);
        }else if("Tablette".equals(os)){
            DefaultComboBoxModel listOs = new DefaultComboBoxModel();
            listOs.addElement("iOS");
            listOs.addElement("Androïd");
            listOs.addElement("Windows");
            selectOs.setModel(listOs);
        }
    }//GEN-LAST:event_selectTypeDevActionPerformed

    private void jBOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOkActionPerformed
        // TODO add your handling code here:
        String devName = jTDevName.getText();
        String typeDev = (String)this.selectTypeDev.getSelectedItem();
        String os = (String)this.selectOs.getSelectedItem();
        String siteName = (String)this.selectSite.getSelectedItem();
        String numRoom = (String)this.selectRoom.getSelectedItem();
        if(("".equals(devName))){
            this.jLerr.setText("Vous avez oublié de remplir un champs");
            this.jLerr.setVisible(true);
        }
        else{
            //test nom equipement d'interco non existant
            boolean exist = DBMana.devExist(devName);
            if(!exist){
                this.jLerr.setText("L'équipement "+devName+" existe déjà");
                this.jLerr.setVisible(true);
            }
            else{
                Devices dev = new Devices (devName, typeDev, os, siteName, numRoom);
                DBMana.AddDBDev(dev);
                this.jLerr.setVisible(false);
                JFAddNetworkCard1 frameAddNC = new JFAddNetworkCard1(devName);
                frameAddNC.setVisible(true);
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_jBOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAddDev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAddDev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAddDev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAddDev.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFAddDev().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBOk;
    private javax.swing.JLabel jImgAddDev;
    private javax.swing.JLabel jLAddDev;
    private javax.swing.JLabel jLDevName;
    private javax.swing.JLabel jLOsDev;
    private javax.swing.JLabel jLRoom;
    private javax.swing.JLabel jLSite;
    private javax.swing.JLabel jLTypeDev;
    private javax.swing.JLabel jLerr;
    private javax.swing.JTextField jTDevName;
    private javax.swing.JComboBox selectOs;
    private javax.swing.JComboBox selectRoom;
    private javax.swing.JComboBox selectSite;
    private javax.swing.JComboBox selectTypeDev;
    // End of variables declaration//GEN-END:variables
}
