/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package package_v3;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author Alexandra
 */
public class JFConfig extends javax.swing.JFrame {

    /**
     * Creates new form JFConfig
     */
    public JFConfig() {
        initComponents();
        this.setResizable(false);
        DefaultComboBoxModel listSite = new DefaultComboBoxModel();
        listSite=DBMana.selectDBSite(listSite);
        DefaultComboBoxModel listSite_2 = new DefaultComboBoxModel();
        listSite_2=DBMana.selectDBSite(listSite_2);
        selectSite1.setModel(listSite);
        selectSite2.setModel(listSite_2);
        String siteName = (String)this.selectSite2.getSelectedItem();
        DefaultComboBoxModel listRoom = new DefaultComboBoxModel();
        listRoom=DBMana.selectDBRoom(listRoom, siteName);
        selectRoom2.setModel(listRoom);
        DefaultComboBoxModel listIntercoDev = new DefaultComboBoxModel();
        listIntercoDev=DBMana.selectDBIntercoDev(listIntercoDev);
        selectIntercoDev3.setModel(listIntercoDev);
        DefaultComboBoxModel listDev = new DefaultComboBoxModel();
        listDev=DBMana.selectDBDev(listDev);
        selectDev4.setModel(listDev);
        DefaultComboBoxModel listDev_2 = new DefaultComboBoxModel();
        listDev_2=DBMana.selectDBDev(listDev_2);
        selectDev5.setModel(listDev_2);
        String dev = (String)this.selectDev5.getSelectedItem();
        DefaultComboBoxModel listNC = new DefaultComboBoxModel();
        listNC=DBMana.selectDBNC(listNC, dev);
        selectNC5.setModel(listNC);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLConf = new javax.swing.JLabel();
        jImgSite = new javax.swing.JLabel();
        jImgRoom = new javax.swing.JLabel();
        jImgDev = new javax.swing.JLabel();
        jImgPc = new javax.swing.JLabel();
        jImgNetCard = new javax.swing.JLabel();
        jBAddSite = new javax.swing.JButton();
        jBAddRoom = new javax.swing.JButton();
        jBAddDev = new javax.swing.JButton();
        jBAddPc = new javax.swing.JButton();
        jBAddNetCard = new javax.swing.JButton();
        selectSite1 = new javax.swing.JComboBox();
        jBSupprSite = new javax.swing.JButton();
        selectSite2 = new javax.swing.JComboBox();
        selectRoom2 = new javax.swing.JComboBox();
        jBSupprRoom = new javax.swing.JButton();
        selectIntercoDev3 = new javax.swing.JComboBox();
        jBSupprIntercoDev = new javax.swing.JButton();
        selectDev4 = new javax.swing.JComboBox();
        jBSupprDev = new javax.swing.JButton();
        selectDev5 = new javax.swing.JComboBox();
        selectNC5 = new javax.swing.JComboBox();
        jBSupprCard = new javax.swing.JButton();

        jLabel3.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLConf.setText("Configuration");

        jImgSite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/site.png"))); // NOI18N

        jImgRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/room.png"))); // NOI18N

        jImgDev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devInterco.png"))); // NOI18N

        jImgPc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/devices.png"))); // NOI18N

        jImgNetCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/card.png"))); // NOI18N

        jBAddSite.setText("Ajout Local");
        jBAddSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddSiteActionPerformed(evt);
            }
        });

        jBAddRoom.setText("Ajout Salle");
        jBAddRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddRoomActionPerformed(evt);
            }
        });

        jBAddDev.setText("Ajout Equipement d'interco");
        jBAddDev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddDevActionPerformed(evt);
            }
        });

        jBAddPc.setText("Ajout Equipement");
        jBAddPc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddPcActionPerformed(evt);
            }
        });

        jBAddNetCard.setText("Ajout Carte");
        jBAddNetCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAddNetCardActionPerformed(evt);
            }
        });

        jBSupprSite.setText("Supprimer Local");
        jBSupprSite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSupprSiteActionPerformed(evt);
            }
        });

        selectSite2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectSite2ActionPerformed(evt);
            }
        });

        jBSupprRoom.setText("Supprimer Salle");
        jBSupprRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSupprRoomActionPerformed(evt);
            }
        });

        jBSupprIntercoDev.setText("Supprimer Equipement d'interco");
        jBSupprIntercoDev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSupprIntercoDevActionPerformed(evt);
            }
        });

        jBSupprDev.setText("Supprimer Equipement");

        selectDev5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDev5ActionPerformed(evt);
            }
        });

        jBSupprCard.setText("Supprimer Carte");
        jBSupprCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSupprCardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jImgSite, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBAddSite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBSupprSite, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectSite1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jImgRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBAddRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selectSite2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selectRoom2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBSupprRoom, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBSupprIntercoDev, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectIntercoDev3, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBAddDev, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jImgDev, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBSupprDev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selectDev4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBAddPc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jImgPc)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBSupprCard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selectDev5, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(selectNC5, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBAddNetCard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jImgNetCard)
                        .addGap(19, 19, 19)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(jLConf, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jImgRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jImgSite, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jImgNetCard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLConf, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jImgPc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jImgDev, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBAddNetCard)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jBAddDev)
                                .addComponent(jBAddPc))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jBAddRoom)
                                .addComponent(jBAddSite)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBSupprCard, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(selectSite2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(selectIntercoDev3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(selectDev5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(selectDev4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(selectSite1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(selectRoom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(selectNC5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jBSupprIntercoDev)
                                    .addComponent(jBSupprRoom)
                                    .addComponent(jBSupprDev)))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBSupprSite)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAddSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddSiteActionPerformed
        // TODO add your handling code here:
        JFAddSite frameAddSite = new JFAddSite();
        this.setVisible(false);
        frameAddSite.setVisible(true);
    }//GEN-LAST:event_jBAddSiteActionPerformed

    private void jBAddRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddRoomActionPerformed
        // TODO add your handling code here:
        JFAddRoom frameAddRoom = new JFAddRoom();
        this.setVisible(false);
        frameAddRoom.setVisible(true);
    }//GEN-LAST:event_jBAddRoomActionPerformed

    private void selectSite2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectSite2ActionPerformed
        // TODO add your handling code here:
        String siteName = (String)this.selectSite2.getSelectedItem();
        DefaultComboBoxModel listSite = new DefaultComboBoxModel();
        listSite=DBMana.selectDBRoom(listSite, siteName);
        selectRoom2.setModel(listSite);
    }//GEN-LAST:event_selectSite2ActionPerformed


    private void jBAddDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddDevActionPerformed
        // TODO add your handling code here:
        JFAddIntercoDev frameAddIntercoDev = new JFAddIntercoDev();
        this.setVisible(false);
        frameAddIntercoDev.setVisible(true);
    }//GEN-LAST:event_jBAddDevActionPerformed

    private void jBSupprCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSupprCardActionPerformed
      
        String macAddr = (String)this.selectNC5.getSelectedItem();
        if(macAddr.isEmpty())
                JOptionPane.showMessageDialog(null, "Veuillez d'abord selectionner une Carte réseau ");
        else
        {
                int option = JOptionPane.showConfirmDialog(null, "Êtes-vous sûr ?", "Suppression en cours", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if(option != JOptionPane.NO_OPTION &&  option != JOptionPane.CLOSED_OPTION)
                     DBMana.supprNCMac(macAddr);
        }   
  
    }//GEN-LAST:event_jBSupprCardActionPerformed


    private void jBSupprSiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSupprSiteActionPerformed
        String site = (String)this.selectSite1.getSelectedItem();
        if(site.isEmpty())
                JOptionPane.showMessageDialog(null, "Veuillez d'abord selectionner un Site ");
        else
        {
                int option = JOptionPane.showConfirmDialog(null, "Êtes-vous sûr ?", "Suppression en cours", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if(option != JOptionPane.NO_OPTION &&  option != JOptionPane.CLOSED_OPTION){
                    DBMana.supprSite(site);
                }
        }   
    }//GEN-LAST:event_jBSupprSiteActionPerformed

    private void jBSupprRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSupprRoomActionPerformed
        String room ;
        int numroom = 1;
        room = (String)this.selectRoom2.getSelectedItem();
        
        if(room instanceof String)
                JOptionPane.showMessageDialog(null, "Veuillez d'abord selectionner un Site ");
        else
        {
                numroom = Integer.decode(room);
                int option = JOptionPane.showConfirmDialog(null, "Êtes-vous sûr ?", "Suppression en cours", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if(option != JOptionPane.NO_OPTION &&  option != JOptionPane.CLOSED_OPTION)
                     DBMana.supprRoom(numroom);
        }   
    }//GEN-LAST:event_jBSupprRoomActionPerformed

    private void jBAddPcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddPcActionPerformed
        // TODO add your handling code here:
        JFAddDev frameAddDev = new JFAddDev();
        this.setVisible(false);
        frameAddDev.setVisible(true);
    }//GEN-LAST:event_jBAddPcActionPerformed

    private void jBAddNetCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAddNetCardActionPerformed
        // TODO add your handling code here:
        JFAddNetworkCard frameAddNC = new JFAddNetworkCard();
        this.setVisible(false);
        frameAddNC.setVisible(true);
    }//GEN-LAST:event_jBAddNetCardActionPerformed

    private void jBSupprIntercoDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSupprIntercoDevActionPerformed
        // TODO add your handling code here:
        String intercoDevName = (String)this.selectIntercoDev3.getSelectedItem();
        int option = JOptionPane.showConfirmDialog(null, "Êtes-vous sûr ?", "Suppression en cours", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if(option != JOptionPane.NO_OPTION &&  option != JOptionPane.CLOSED_OPTION){
                    DBMana.supprInterCoDevName(intercoDevName);
                    DefaultComboBoxModel listIntercoDev = new DefaultComboBoxModel();
                    listIntercoDev=DBMana.selectDBIntercoDev(listIntercoDev);
                    selectIntercoDev3.setModel(listIntercoDev);
                }
    }//GEN-LAST:event_jBSupprIntercoDevActionPerformed

    private void selectDev5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectDev5ActionPerformed
        // TODO add your handling code here:
        String dev = (String)this.selectDev5.getSelectedItem();
        DefaultComboBoxModel listNC = new DefaultComboBoxModel();
        listNC=DBMana.selectDBNC(listNC, dev);
        selectNC5.setModel(listNC);
    }//GEN-LAST:event_selectDev5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFConfig().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAddDev;
    private javax.swing.JButton jBAddNetCard;
    private javax.swing.JButton jBAddPc;
    private javax.swing.JButton jBAddRoom;
    private javax.swing.JButton jBAddSite;
    private javax.swing.JButton jBSupprCard;
    private javax.swing.JButton jBSupprDev;
    private javax.swing.JButton jBSupprIntercoDev;
    private javax.swing.JButton jBSupprRoom;
    private javax.swing.JButton jBSupprSite;
    private javax.swing.JLabel jImgDev;
    private javax.swing.JLabel jImgNetCard;
    private javax.swing.JLabel jImgPc;
    private javax.swing.JLabel jImgRoom;
    private javax.swing.JLabel jImgSite;
    private javax.swing.JLabel jLConf;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox selectDev4;
    private javax.swing.JComboBox selectDev5;
    private javax.swing.JComboBox selectIntercoDev3;
    private javax.swing.JComboBox selectNC5;
    private javax.swing.JComboBox selectRoom2;
    private javax.swing.JComboBox selectSite1;
    private javax.swing.JComboBox selectSite2;
    // End of variables declaration//GEN-END:variables
}
