/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package version1;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Alexandra
 */
public class JFFicheUtilisateur extends javax.swing.JFrame {
    private String nom;
    private String idrech;
    ClientConnect client;
    private String nomprop;
    /**
     * Creates new form JFFicheUtilisateur
     */
    public JFFicheUtilisateur(String nom, Object c, String nomprop) {
        initComponents();
        this.nom=nom;
        this.nomprop=nomprop;
        this.client = (ClientConnect) c;
        String req = "GETINFO2 "+nom;
        System.out.println(req);
        try {
            String info = client.communiquer(req);
            String msg[] = info.split(" ");
            jnom.setText(msg[1]);
            jprenom.setText(msg[2]);
            jmail.setText(msg[3]);
            jtel.setText(msg[4]);
            jnais.setText(msg[5]);
            idrech = msg[6];
            
            
            String req3 = "GETINFOUSERDIP "+idrech;
            String compt = client.communiquer(req3);
            
            String msgd[] = compt.split(" ");
            
            //System.out.println("err : "+msg[1]);
            if ("null".equals(msgd[1])){
                System.out.println("Auncun diplome trouvé");
            } else {
                DefaultListModel modeldip = new DefaultListModel();
                modeldip.addElement(msgd[1]+" "+msgd[2]);
                jLDip.setModel(modeldip);
            }
            String req4 = "GETINFOUSERCOMP "+idrech;
            String dip = client.communiquer(req4);
            
            String msgc[] = dip.split(" ");
            
            //System.out.println("err : "+msg[1]);
            if ("null".equals(msgc[1])){
                System.out.println("Auncune compétence trouvé");
            }else{
                DefaultListModel modelcom = new DefaultListModel();
                modelcom.addElement(msgc[1]+" "+msgc[2]); 
                jLComp.setModel(modelcom);
            }
      
            
        } catch (IOException ex) {
            Logger.getLogger(JFApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rech = new javax.swing.JLabel();
        jnom = new javax.swing.JLabel();
        jprenom = new javax.swing.JLabel();
        jmail = new javax.swing.JLabel();
        jtel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLComp = new javax.swing.JList<>();
        jcomp = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLDip = new javax.swing.JList<>();
        jdiplome = new javax.swing.JLabel();
        jnais = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        messErr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rech.setText("Utilisateur recherché");

        jnom.setText("Nom");

        jprenom.setText("Prénom");

        jmail.setText("Mail : ");

        jtel.setText("Téléphone : ");

        jLComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLCompMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jLComp);

        jcomp.setText("Compétences : ");

        jScrollPane2.setViewportView(jLDip);

        jdiplome.setText("Diplômes : ");

        jnais.setText("Naissance :");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(rech))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jnom))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jprenom))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jcomp)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jdiplome)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 19, Short.MAX_VALUE)
                                .addComponent(messErr, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jmail)
                            .addComponent(jnais)
                            .addComponent(jtel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rech)
                    .addComponent(messErr, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jnom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jprenom)
                .addGap(18, 18, 18)
                .addComponent(jmail)
                .addGap(18, 18, 18)
                .addComponent(jtel)
                .addGap(16, 16, 16)
                .addComponent(jnais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcomp)
                    .addComponent(jdiplome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLCompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLCompMouseClicked

        try {
            String req = "ADDLIKE "+idrech+" "+nomprop;
            String rep = client.communiquer(req);
            System.out.println(rep);
            String msg[] = rep.split(" ");
            if("ERR200".equals(msg[1])){
                messErr.setText("Erreur Ajout !");
                messErr.setVisible(true);
            }else{
                JFValidateLike valide = new  JFValidateLike();
                valide.setVisible(true);
            }
        } catch (IOException ex) {
            Logger.getLogger(JFFicheUtilisateur.class.getName()).log(Level.SEVERE, null, ex);
        }
     
      
          
    }//GEN-LAST:event_jLCompMouseClicked
    
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jLComp;
    private javax.swing.JList<String> jLDip;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jcomp;
    private javax.swing.JLabel jdiplome;
    private javax.swing.JLabel jmail;
    private javax.swing.JLabel jnais;
    private javax.swing.JLabel jnom;
    private javax.swing.JLabel jprenom;
    private javax.swing.JLabel jtel;
    private javax.swing.JLabel messErr;
    private javax.swing.JLabel rech;
    // End of variables declaration//GEN-END:variables
}
