/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package version1;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Alexandra
 */
public class JFFicheUtilisateur extends javax.swing.JFrame {
    private String nom;
    ClientConnect client;
    /**
     * Creates new form JFFicheUtilisateur
     */
    public JFFicheUtilisateur(String nom, Object c) {
        initComponents();
        this.nom=nom;
        this.client = (ClientConnect) c;
        String req = "GETINFO2 "+nom;
        System.out.println(req);
        try {
            String info = client.communiquer(req);
            String msg[] = info.split(" ");
            jnom.setText(msg[1]);
            jprenom.setText(msg[2]);
            jmail.setText(msg[3]);
            jtel.setText(msg[4]);
            jnais.setText(msg[5]);
        } catch (IOException ex) {
            Logger.getLogger(JFApp.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rech = new javax.swing.JLabel();
        jnom = new javax.swing.JLabel();
        jprenom = new javax.swing.JLabel();
        jmail = new javax.swing.JLabel();
        jnaiss = new javax.swing.JLabel();
        jtel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListComp = new javax.swing.JList<>();
        jcomp = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListDiplome = new javax.swing.JList<>();
        jdiplome = new javax.swing.JLabel();
        jnais = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rech.setText("Utilisateur recherché");

        jnom.setText("Nom");

        jprenom.setText("Prénom");

        jmail.setText("Mail : ");

        jnaiss.setText("Naissance : ");

        jtel.setText("Téléphone : ");

        jScrollPane1.setViewportView(jListComp);

        jcomp.setText("Compétences : ");

        jScrollPane2.setViewportView(jListDiplome);

        jdiplome.setText("Diplômes : ");

        jnais.setText("Naissance :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(rech))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jnom))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jprenom)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jnaiss)
                                    .addComponent(jmail)
                                    .addComponent(jtel)
                                    .addComponent(jnais)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jcomp)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jdiplome)
                        .addGap(0, 133, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rech)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jnom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jprenom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jnaiss)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jnais)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcomp)
                    .addComponent(jdiplome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jListComp;
    private javax.swing.JList<String> jListDiplome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jcomp;
    private javax.swing.JLabel jdiplome;
    private javax.swing.JLabel jmail;
    private javax.swing.JLabel jnais;
    private javax.swing.JLabel jnaiss;
    private javax.swing.JLabel jnom;
    private javax.swing.JLabel jprenom;
    private javax.swing.JLabel jtel;
    private javax.swing.JLabel rech;
    // End of variables declaration//GEN-END:variables
}
