/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package version1;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Brice
 */
public class JFInscription extends javax.swing.JFrame {

    
    ClientConnect client1;
    private final static int Port = 7;
    /**
     * 
     * Creates new form JFInscription
     */
    public JFInscription() {
        initComponents();
        messErr.setVisible(false);
        messErr.setForeground(Color.red);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jmdp2 = new javax.swing.JTextField();
        jmdp = new javax.swing.JTextField();
        jpseudo = new javax.swing.JTextField();
        jmail = new javax.swing.JTextField();
        jphone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jnom = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jprenom = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jnaissance = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        messErr = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jCphone = new javax.swing.JComboBox<>();
        jCnais = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pseudo : ");

        jLabel2.setText("Mot de passe : ");

        jLabel3.setText("Confirmation du mot de passe : ");

        jLabel4.setText("Mail :");

        jLabel5.setText("Date de naissance : ");

        jLabel6.setText("Inscription");

        jLabel7.setText("Nom : ");

        jLabel8.setText("Prénom : ");

        jLabel9.setText("Téléphone : ");

        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        messErr.setText("messErr");

        jLabel10.setText("(YYYY-MM-DD)");

        jLabel11.setText("Visibilité :");

        jLabel12.setText("Visibilité :");

        jCphone.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User", "Tous" }));

        jCnais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User", "Tous" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(messErr))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jnaissance, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCnais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jphone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jmdp2)
                                .addComponent(jmdp)
                                .addComponent(jpseudo)
                                .addComponent(jnom)
                                .addComponent(jprenom)
                                .addComponent(jmail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jButton1)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(messErr)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jpseudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jmdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jmdp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jprenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jCphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jnaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jCnais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try {
         client1 = new ClientConnect(Port);
         // DECLARATION VARIABLE 
         String id = null;
         String pseudo = jpseudo.getText();
         String pass = jmdp.getText();
         String nom = jnom.getText();
         String prenom = jprenom.getText();
         String mail = jmail.getText();
         String phone = jphone.getText();
         String naissance = jnaissance.getText();
         
         //VERIFICATION CHAMPS NON VIDE
         if ( (pseudo.equals(""))||(pass.equals(""))||(mail.equals(""))||(phone.equals(""))||(naissance.equals(""))||(nom.equals(""))||(prenom.equals(""))){
          messErr.setText("Completer l'ensemble des Champs ");
          messErr.setVisible(true); 
         } else {
             if(!pass.equals(jmdp2.getText())){
                 
             }else {
                 
             
             
                  String req;
         int visible = 0;
         //VERIFICATION VISIBILITE
         if(jCphone.getSelectedItem().equals("Admin"))
             visible = 100;
         if(jCphone.getSelectedItem().equals("User"))  
             visible = 200;
         if(jCphone.getSelectedItem().equals("Tous")) 
             visible = 300;
         if(jCnais.getSelectedItem().equals("Admin"))
             visible = visible + 1;
         if(jCnais.getSelectedItem().equals("User"))  
             visible = visible + 2;
         if(jCnais.getSelectedItem().equals("Tous")) 
             visible = visible + 3;
         System.out.println(visible);
         // Champ visiblilité 101/102/103 201/202/203 301/302/303
         
         // Création d'un nouvell utilisateur
         req = "NEWAUTH "+pseudo+" "+pass;
         String rep = client1.communiquer(req);
         System.out.println(rep);
         
         // VERIFICATION REPONSE 
         String msg[] = rep.split(" ");
                if("ERR200".equals(msg[1])){
                messErr.setText("Erreur Creation");
                messErr.setVisible(true);
            }else{
          // Connexion pour récupérer ID AVEC LA REQUETE AUTH
         String req1 = "AUTH "+pseudo+" "+pass;
         String Id = client1.communiquer(req1);
         //AFFICHAGE TEST
         System.out.println(Id);
         // VERIFICATION REPONSE 
         String msg1[] = Id.split(" ");
         //AFFICHAGE TEST
         System.out.println(msg1[1]);
         if("ERR200".equals(msg1[1])){
                messErr.setText("Erreur Creation");
                messErr.setVisible(true);
            }else{
         // REQUETE NEWUSER POUR RENSEIGNER LA BASE DE DONNEE UTILISATEUR    
         String req2;
         req2 = "NEWUSER "+msg1[1]+" "+prenom+" "+nom+" "+mail+" "+phone+" "+naissance+" "+visible;
         System.out.println(req2);
         String retour =  client1.communiquer(req2);
         System.out.println(retour);
         // VERIFICATION
         String msg2[] = retour.split(" "); 
         if("true".equals(msg2[1])){
               // AFFICHAGE De la PAGE UNE FOIS CONNECT (Envoie de l'id)
               this.setVisible(false);
               JFApp app = new JFApp(msg1[1],client1);
               app.setVisible(true);
               // AFFICHAGE VALIDATION INSCRIPTION
               JFValidate valide = new JFValidate();
               valide.setVisible(true); 
               
            }
            else{
                // AFFICHAGE MESSAGE ERREUR
                messErr.setText("Erreur Creation");
                messErr.setVisible(true);
            }
        }
        }
        }
        }
        }catch (IOException ex) {
            Logger.getLogger(JFInscription.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCnais;
    private javax.swing.JComboBox<String> jCphone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jmail;
    private javax.swing.JTextField jmdp;
    private javax.swing.JTextField jmdp2;
    private javax.swing.JTextField jnaissance;
    private javax.swing.JTextField jnom;
    private javax.swing.JTextField jphone;
    private javax.swing.JTextField jprenom;
    private javax.swing.JTextField jpseudo;
    private javax.swing.JLabel messErr;
    // End of variables declaration//GEN-END:variables
}
